Repository BulbProject/bulb-project-frontend, pull requests merged in 2020-04, with the labels that each got.

#1 feat: Add configuration to project
  .babelrc
  .editorconfig
  .eslintignore
  .eslintrc.json
  .prettierignore
  .prettierrc.json
  Dockerfile
  docker-compose.yml
  next.config.js
  package.json
  pages/_app.tsx
  pages/_document.tsx
  pages/index.tsx
  tsconfig.json
  yarn.lock
Labels: enhancement

#2 Feat: Setup project as pwa
  .gitignore
  next.config.js
  package.json
  pages/_app.tsx
  public/android-chrome-192x192.png
  public/android-chrome-512x512.png
  public/apple-touch-icon.png
  public/browserconfig.xml
  public/favicon-16x16.png
  public/favicon-32x32.png
  public/favicon.ico
  public/manifest.json
  public/mstile-150x150.png
  public/safari-pinned-tab.svg
Labels: enhancement

#3 feat: Add layout
  components/Layout/index.tsx
  components/Layout/styles.ts
  pages/_app.tsx
  pages/_document.tsx
  public/assets/images/logo.svg
Labels: enhancement

#13 feat: (Categories List) add categories list
  .babelrc.js
  package.json
  src/assets/icons/reload.inline.svg
  src/components/Categories/Cards/BaseCard.tsx
  src/components/Categories/Cards/Card.tsx
  src/components/Categories/Cards/ErrorCard.tsx
  src/components/Categories/Cards/StubCard.tsx
  src/components/Categories/Cards/index.ts
  src/components/Categories/Cards/types.d.ts
  src/components/Categories/error.tsx
  src/components/Classification/index.tsx
  src/components/Classification/styles.ts
  src/components/Container/config.ts
  src/components/Container/index.tsx
  src/components/Container/styles.ts
  src/config.ts
  src/index.tsx
  src/pages/index.tsx
  src/styles/categories.ts
  src/types/data/categories-list-entity.d.ts
  src/types/data/index.d.ts
  src/utils/get-random-width.ts
  src/utils/index.ts
  yarn.lock
Labels: enhancement

#15 feat(Info Page): add info pages
  .gitignore
  info/demo-markdown.md
  package.json
  public/index.html
  src/assets/icons/arrow.svg
  src/assets/icons/refresh.svg
  src/components/Layout/components/Aside/index.tsx
  src/components/Layout/components/Aside/styles.ts
  src/components/Layout/index.tsx
  src/components/Layout/styles.ts
  src/components/markdown/renderers.tsx
  src/components/markdown/styles.ts
  src/config.ts
  src/index.tsx
  src/pages/info/infoPage.tsx
  src/pages/info/styles.ts
  src/routes.ts
  src/utils/get-random-width.ts
  src/utils/index.ts
  src/utils/kebab-case-to-sentence-case.ts
  src/utils/string-to-kebab-case.ts
  webpack.common.js
  webpack.prod.js
  yarn.lock
Labels: enhancement

#14 feat(NotFound Page): add NotFound page
  src/components/Categories/Cards/StubCard.tsx
  src/pages/notFound/index.tsx
  src/pages/notFound/styles.ts
  src/routes.ts
  yarn.lock
Labels: enhancement

#17 feat(ErrorBoundary): add error boundary
  src/components/ErrorBoundary/components/ErrorPage.tsx
  src/components/ErrorBoundary/components/index.ts
  src/components/ErrorBoundary/components/styles.ts
  src/components/ErrorBoundary/index.tsx
  src/components/ErrorBoundary/props.d.ts
  src/pages/categories/category/index.tsx
  src/pages/index.tsx
Labels: enhancement

#19 feat(Deploy): actualization deploy config
  .dockerignore
  .eslintignore
  .gitignore
  Dockerfile
  nginx.conf.template
  package.json
  webpack.common.js
  webpack.dev.js
  webpack.prod.js
  yarn.lock
Labels: enhancement

#21 feat: Add animation for pages
  package.json
  src/components/FadeIn/index.tsx
  src/components/Layout/components/Aside/index.tsx
  src/index.tsx
  src/pages/categories/category/components/Stepper/components/Overlay/index.tsx
  src/pages/categories/category/components/Stepper/index.tsx
  src/pages/categories/category/index.tsx
  src/pages/index.tsx
  src/pages/info/infoPage.tsx
  src/styles/categories.ts
  yarn.lock
Labels: enhancement

#27 refactor: Refactor Info page
  src/assets/icons/arrow.inline.svg
  src/assets/icons/refresh.svg
  src/pages/info/Info.component.tsx
  src/pages/info/Info.styles.ts
Labels: page:info, scope:pages, scope:styles

#28 refactor: Refactor shared components
  src/shared/Classification/Classification.component.tsx
  src/shared/Classification/Classification.styles.ts
  src/shared/Container/Container.component.tsx
  src/shared/Container/Container.styles.ts
Labels: refactor, scope:components, scope:styles

#29 feat: Added styles like prozorro
  package.json
  public/favicon.svg
  public/index.html
  src/assets/images/logo.svg
  src/components/Aside/Aside.component.tsx
  src/components/GlobalStyles/GlobalStyles.component.ts
  src/components/GlobalStyles/index.ts
  src/components/Layout/Layout.component.tsx
  src/components/Layout/Layout.styles.ts
  src/components/index.ts
  src/index.tsx
  src/pages/category/Category.component.tsx
  src/pages/category/Category.styles.ts
  src/pages/category/modules/Form/components/Requirement/Requirement.component.tsx
  src/pages/category/modules/Form/components/Requirement/Requirement.module.tsx
  src/pages/category/modules/Form/components/Requirement/Requirement.types.d.ts
  src/pages/info/modules/Markdown/Markdown.component.tsx
  src/pages/info/modules/Markdown/Markdown.styles.ts
  src/pages/main/modules/Card/Card.styles.ts
  src/shared/Classification/Classification.component.tsx
  src/shared/Classification/Classification.styles.ts
  src/typings.d.ts
  webpack.common.js
  yarn.lock
Labels: bugfix, scope:styles

#30 feat: Add Ukrainian translation
  src/components/Aside/Aside.component.tsx
  src/components/ErrorPage/ErrorPage.component.tsx
  src/pages/category/Category.component.tsx
  src/pages/category/modules/Form/components/Requirement/Requirement.module.tsx
  src/pages/category/modules/Form/components/RequirementGroup/RequirementGroup.component.tsx
  src/pages/category/modules/Form/components/RequirementGroup/RequirementGroup.types.d.ts
  src/pages/category/modules/Stepper/Stepper.component.tsx
  src/pages/info/Info.component.tsx
  src/pages/main/Main.component.tsx
  src/pages/main/modules/Error/Error.component.tsx
  src/pages/notFound/NotFount.component.tsx
Labels: feature, misc

#31 fix: Fix type declarations off of external library
  src/pages/category/modules/Form/components/RequirementGroup/RequirementGroup.component.tsx
  src/types/data/criterion.d.ts
  src/types/data/index.d.ts
  src/types/data/requested-need.d.ts
  src/types/data/requirement-group.d.ts
Labels: bugfix, scope:types

#32 feat(Layout): add contact info to header and footer
  src/assets/icons/facebook.inline.svg
  src/assets/icons/instagram.inline.svg
  src/assets/icons/slideshare.inline.svg
  src/assets/icons/twitter.inline.svg
  src/assets/icons/youtube.inline.svg
  src/components/Layout/Layout.component.tsx
  src/components/Layout/Layout.styles.ts
  src/components/SocialLinks/SocialLinks.component.tsx
  src/components/SocialLinks/SocialLinks.styles.ts
  src/components/SocialLinks/index.ts
Labels: feature
