Repository BulbProject/bulb-project-frontend, pull requests merged in 2020-10, with the labels that each got.

#108 feat: Add i18n initialize
  package.json
  public/locales/en/common.json
  public/locales/ua/common.json
  src/core/layout/header/header.component.tsx
  src/i18n.ts
  src/index.tsx
  src/shared/components/language-select/index.ts
  src/shared/components/language-select/language-select.component.tsx
  src/shared/components/language-select/language-select.styles.ts
  webpack.dev.js
  webpack.prod.js
  yarn.lock
Labels: feature

#110 feat: Add translations and fallback for form
  .eslintrc.js
  public/locales/en/button.json
  public/locales/en/calculation-result.json
  public/locales/en/categories-list-component.json
  public/locales/en/common.json
  public/locales/en/criterion.json
  public/locales/en/filter-drawer.json
  public/locales/en/hero.json
  public/locales/en/id-modal.json
  public/locales/en/item.json
  public/locales/en/items.json
  public/locales/en/requested-need.json
  public/locales/en/specification.json
  public/locales/ua/button.json
  public/locales/ua/calculation-result.json
  public/locales/ua/categories-list-component.json
  public/locales/ua/common.json
  public/locales/ua/criterion.json
  public/locales/ua/filter-drawer.json
  public/locales/ua/hero.json
  public/locales/ua/id-modal.json
  public/locales/ua/item.json
  public/locales/ua/items.json
  public/locales/ua/requested-need.json
  public/locales/ua/specification.json
  src/core/context/category-provider/category-provider.context.tsx
  src/core/layout/footer/footer.component.tsx
  src/core/layout/header/aside/aside.component.tsx
  src/i18n.ts
  src/modules/calculation-result/calculation-result.component.tsx
  src/modules/calculation-result/filter-drawer/filter-drawer.component.tsx
  src/modules/calculation-result/filter/filter.component.tsx
  src/modules/calculation-result/item/item.component.tsx
  src/modules/calculation-result/items/items.component.tsx
  src/modules/calculation-result/requested-need/requested-need.component.tsx
  src/modules/calculation-result/specification/form-modal/form-modal.component.tsx
  src/modules/calculation-result/specification/id-modal/id-modal.component.tsx
  src/modules/calculation-result/specification/specification.component.tsx
  src/modules/categories-list/categories-list.component.tsx
  src/modules/categories-list/error/error.component.tsx
  src/modules/category/form/buttons/back-button/back-button.component.tsx
  src/modules/category/form/buttons/forward-button/forward-button.component.tsx
  src/modules/category/form/criteria/criterion/criterion.component.tsx
  src/modules/resource/resource.component.tsx
  src/shared/components/error-page/error-page.component.tsx
  src/shared/components/language-select/language-select.component.tsx
  src/shared/components/language-select/language-select.styles.ts
  src/shared/components/requirement/input/option-group/option-group.component.tsx
  src/shared/context/calculation/calculation.context.tsx
Labels: feature

#117 refactor: Refactor language-select appearance
  src/shared/components/language-select/language-select.styles.ts
Labels: refactor, scope:styles

#118 Payback calculator
  public/locales/en/item.json
  public/locales/ua/item.json
  src/i18n.ts
  src/modules/calculation-result/item/calculation-modal/calculation-modal.component.tsx
  src/modules/calculation-result/item/calculation-modal/calculation-modal.styles.ts
  src/modules/calculation-result/item/calculation-modal/index.ts
  src/modules/calculation-result/item/item.component.tsx
Labels: feature

#119 0.4.0
  .eslintrc.js
  public/locales/en/main.json
  public/locales/ua/common.json
  public/locales/ua/main.json
  src/modules/calculation-result/item/calculation-modal/calculation-modal.component.tsx
  src/modules/calculation-result/item/calculation-modal/calculation-modal.styles.ts
  src/modules/calculation-result/item/calculation-modal/index.ts
  src/shared/components/requirement/input/input.component.tsx
Labels: bugfix, feature, page:calculation-result, refactor, scope:components, scope:pages

#122 refactor: Remove types for formData
  src/modules/calculation-result/item/calculation-modal/calculation-modal.component.tsx
  src/modules/calculation-result/item/item.component.tsx
Labels: refactor
